package com.souchanrojame.librarymanagement.controller;

import com.souchanrojame.librarymanagement.model.Book;
import com.souchanrojame.librarymanagement.repository.BookRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.web.bind.annotation.*;
import java.util.*;

@RestController
@RequestMapping("/api/ai")
@RequiredArgsConstructor
@CrossOrigin(origins = "http://localhost:3000")
public class AiController {
    private final BookRepository bookRepository;

    @PostMapping("/summarize")
    public Map<String, String> summarize(@RequestBody Map<String, String> body) {
        String isbn = body.get("isbn");
        Book book = bookRepository.findById(isbn).orElse(null);

        if (book == null) {
            return Map.of("summary", "I couldn't find this book in the library database.");
        }

        String title = book.getTitle() != null ? book.getTitle() : "Untitled";
        String desc = book.getDescription() != null ? book.getDescription() : "";
        String category = book.getCategory() != null ? book.getCategory().getCategoryName() : "General";
        String authors = "";
        if (book.getAuthors() != null && !book.getAuthors().isEmpty()) {
            authors = book.getAuthors().stream()
                    .map(a -> a.getFirstName() + " " + a.getLastName())
                    .reduce((a, b) -> a + ", " + b)
                    .orElse("Unknown");
        }

        StringBuilder summary = new StringBuilder();
        summary.append("📚 **Book Summary: ").append(title).append("**\n\n");

        if (!authors.isEmpty()) {
            summary.append("**Author(s):** ").append(authors).append("\n");
        }
        summary.append("**Category:** ").append(category).append("\n");
        summary.append("**Format:** ").append(book.getBookType()).append("\n\n");

        if (!desc.isEmpty()) {
            summary.append("**Overview:**\n").append(desc).append("\n\n");
        }

        summary.append("**Key Highlights:**\n");
        summary.append("• This book is categorized under ").append(category).append(".\n");
        summary.append("• It is available in ").append(book.getBookType().toString().toLowerCase()).append(" format.\n");

        if (book.getEdition() != null) {
            summary.append("• Current edition: ").append(book.getEdition()).append(".\n");
        }
        if (book.getPrice() != null) {
            summary.append("• Price: $").append(book.getPrice()).append(".\n");
        }

        summary.append("\nThis summary was generated by the Library AI Assistant based on available book metadata.");

        return Map.of("summary", summary.toString());
    }

    @PostMapping("/ask")
    public Map<String, String> ask(@RequestBody Map<String, String> body) {
        String question = body.getOrDefault("question", "").toLowerCase();

        String response = generateResponse(question);
        return Map.of("response", response);
    }

    private String generateResponse(String question) {
        if (question.contains("hello") || question.contains("hi") || question.contains("hey")) {
            return "Hello! 👋 I'm the Library AI Assistant. I can help you with:\n\n" +
                    "• **Book recommendations** - Ask me to suggest books\n" +
                    "• **Book summaries** - Click 'Summarize' on any book page\n" +
                    "• **Library information** - Ask about borrowing policies, hours, etc.\n" +
                    "• **Reading suggestions** - Tell me what genres you like\n\n" +
                    "How can I help you today?";
        }

        if (question.contains("recommend") || question.contains("suggest") || question.contains("what should i read")) {
            return "📖 **Book Recommendations:**\n\n" +
                    "Based on popular choices in our library:\n\n" +
                    "1. **\"Clean Code\"** by Robert C. Martin - A must-read for developers\n" +
                    "2. **\"The Pragmatic Programmer\"** by David Thomas - Timeless programming wisdom\n" +
                    "3. **\"Design Patterns\"** by Gang of Four - Essential software design patterns\n" +
                    "4. **\"Introduction to Algorithms\"** by Cormen et al. - Comprehensive algorithms reference\n" +
                    "5. **\"The Art of Computer Programming\"** by Donald Knuth - A classic masterpiece\n\n" +
                    "Would you like more specific recommendations? Tell me your preferred genre or topic!";
        }

        if (question.contains("borrow") || question.contains("loan") || question.contains("how to")) {
            return "📋 **Borrowing Guide:**\n\n" +
                    "1. **Browse** our catalog to find books you're interested in\n" +
                    "2. **Click** on a book to view its details\n" +
                    "3. **Click 'Borrow Now'** to check out the book\n" +
                    "4. **Return** the book before the due date to avoid fines\n\n" +
                    "**Policies:**\n" +
                    "• Loan period: 7 days by default\n" +
                    "• Overdue fine: $1.50 per day\n" +
                    "• You can reserve books that are currently borrowed\n" +
                    "• Digital books can be read online immediately\n\n" +
                    "Need help with something specific?";
        }

        if (question.contains("hour") || question.contains("open") || question.contains("close")) {
            return "🕐 **Library Hours:**\n\n" +
                    "• **Monday - Friday:** 8:00 AM - 8:00 PM\n" +
                    "• **Saturday:** 9:00 AM - 5:00 PM\n" +
                    "• **Sunday:** 10:00 AM - 4:00 PM\n" +
                    "• **Holidays:** Closed\n\n" +
                    "Digital books are available 24/7 online!";
        }

        if (question.contains("java") || question.contains("programming") || question.contains("code") || question.contains("python")) {
            return "💻 **Programming Resources:**\n\n" +
                    "Our library has an excellent collection of programming books:\n\n" +
                    "• **Java:** \"Effective Java\", \"Head First Java\", \"Java Concurrency in Practice\"\n" +
                    "• **Python:** \"Python Crash Course\", \"Fluent Python\", \"Automate the Boring Stuff\"\n" +
                    "• **Web Development:** \"JavaScript: The Good Parts\", \"Learning React\"\n" +
                    "• **Data Science:** \"Python for Data Analysis\", \"Hands-On Machine Learning\"\n\n" +
                    "You can search for these titles in our catalog. Many are available as e-books for instant reading!";
        }

        if (question.contains("help") || question.contains("what can you do") || question.contains("feature")) {
            return "🤖 **Library AI Assistant Capabilities:**\n\n" +
                    "I can help you with:\n\n" +
                    "1. **📚 Book Summaries** - Get a quick overview of any book\n" +
                    "2. **💡 Recommendations** - Get personalized reading suggestions\n" +
                    "3. **📋 Library Info** - Learn about borrowing policies and hours\n" +
                    "4. **🔍 Search Help** - Find books by topic, author, or genre\n" +
                    "5. **❓ General Q&A** - Ask anything about our library services\n\n" +
                    "Try asking me something like:\n" +
                    "• \"Recommend some science fiction books\"\n" +
                    "• \"How do I borrow a book?\"\n" +
                    "• \"What are the library hours?\"";
        }

        if (question.contains("thank")) {
            return "You're welcome! 😊 Feel free to ask if you need anything else. Happy reading! 📖";
        }

        // Default response
        return "I appreciate your question! While I'm a demo AI assistant with limited knowledge, here's what I can help with:\n\n" +
                "• **Book recommendations** - \"Suggest books about [topic]\"\n" +
                "• **Library policies** - \"How do I borrow a book?\"\n" +
                "• **Book summaries** - Use the 'Summarize' button on book detail pages\n" +
                "• **General help** - \"What can you do?\"\n\n" +
                "Try rephrasing your question or ask about one of these topics! 📚";
    }
}
